### ISSUE TITLE
K562 assembly

### ISSUE THREAD

**Issue by canfirtina** [hlxie/sc-Assembly#1]
Dear Xie et al.,

Thanks for your great work. I enjoyed reading your paper.

I noticed that you have made only the HG002 reads available in the SRA. Would it be possible for you to share the assemblies as well? I am particularly interested in the K562 assembly.

Thanks,
Can

**Comment by hlxie** [comment]
Thank you for your interest in single-cell genome assembly. I will upload K562 assembly contig soon.

**Comment by hlxie** [comment]
Thank you for your interest in single-cell genome assembly. I will upload K562 assembly contig soon.

**Comment by canfirtina** [comment]
@hlxie Thanks a lot! Any updates on this?

**Comment by hlxie** [comment]
The assembly contigs of K562 have been deposited in the Sequence Read Archive (SRA) under BioProject: PRJNA800164 (https://www.ncbi.nlm.nih.gov/sra?LinkName=biosample_sra&from_uid=25232871)

**Comment by canfirtina** [comment]
This is great. Thanks a lot!
